### PR TITLE
Make it transparent to the module whether it uses sims.ocs or not.

### PR DESCRIPTION
**Pull request by tribeiro**
Imported and striped down modules directly from sims.ocs so the features will be available but removes module dependency. A warning message is issue when no sims.ocs module is available.

Tested on example_inspection notebook.

### CODE REVIEW

**Comment by dhroth** [comment]
I know it's annoying to depend on sims.ocs, but copy pasting their code into this repo seems like a recipe for disaster. What happens when sims_ocs silently fixes a bug in their code that subtly changes seeing values or swaps seeing/cloud databases?

Isn't the right solution to get sims_ocs to make DDS/salpy optional so that it's easy to install?

**Comment by yoachim** [comment]
Yeah, I think I agree that we don't want to have the same code and databases in 2 repos. One option is to bury the salpy imports in `sims_ocs` so it's easy to use, or we can just make a new repo (maybe `sims_ocs_data`?), and then both `speedObservatory` and `sims_ocs` can depend on that. 

This would also be a good time to check that I actually put in the downtime and weather correctly in `speedObservatory`--I think I'm getting more nights than standard OpSim runs, and I'm not sure why.

**Comment by rhiannonlynne** [comment]
If it were up to me: speedObservatory would go away. 
sims_ocs would be a transparent, easy to use layer on top of ts_observatory_model and a (new) weather/downtime package. 
sims_ocs would just use these packages, and interpret them appropriately for the scheduler code (adding DDS as an *option* -- you can always try/except the import!). 
sims_ocs would be used by all schedulers, with DDS on or off according to usage. 
Having the observatory model and weather/downtime as separate packages makes it easy to upgrade/swap them when the time comes. (i.e. we get spatially resolved clouds). 
We would add the vectorized version of Daniel's slewtime calculation to ts_observatory_model as a "approximateSlewTime" function, which you would call when you want a quick estimate of the slewtime, without it being broken down into all the details and without needing the info about cable wrap. 
If there are other things in speedObservatory which we need (if the lookup table for airmass is easier to use than just calculating the airmass, for example), then we figure out how to include those somewhere.

**Comment by tribeiro** [comment]
I agree that it is not optimal to have a copy of one module inside another. The best option would definitely be to extract that part from sims_ocs and have it as a standalone software, as @yoachim suggested. 

In any case, note that the code imported here only provides an interface o the databases, not the logic behind any calculation. Therefore, unless there is a silent change in the interface (which would also requires changing the code here) a change in the database would not be a big problem. You could easily import any database and load it with this module. In fact, it is possible to exclude the databases from this repository and have the user download it from sims.ocs. The important part, in my opinion, is to be able to run it full-featured without the need to install sims.ocs. 

Also, if the user has a strong urge to be updated on sims.ocs, he might as well install sims.ocs.

**Comment by tribeiro** [comment]
There are indeed calculations going on there! Sorry, my bad!

**Comment by rhiannonlynne** [comment]
I'm a little confused about what the goal was here though, so I may not really understand what this PR is intended to do. 
Is it to increase the fidelity of the speedObservatory?  Understandably, a goal has to be to get all schedulers to use the *same code* as the standard code (which is why I think speedObservatory should go away and we should make sims_ocs / associated packages more easily usable, rather than patching speedObservatory further). I guess that's a design question we should talk about at the face-to-face meeting though.
It is probably good to understand where/why there are differences between speedObservatory and sims_ocs.

**Comment by tribeiro** [comment]
The problem I was trying to solve was to make it run without the need to have sims.ocs installed, but still be able to access seeing, cloud and downtime information. There is a no_ocs branch that @yoachim did but, as it is, you loose those.

**Comment by dhroth** [comment]
I agree with @rhiannonlynne that ideally speedObservatory would go away and SOCS would just run 3 orders of magnitude faster and also not require DDS (and at least the first part would be a relatively easy change to make). There was a couple-line fix to sims_ocs that dramatically sped up seeing and cloud computation, and I submitted that as a PR a while back instead of including it only in speedObservatory. I would be happy if my slew code made it into sims_ocs the same way. 

FYI, the slew times that my code in speedObservatory calculates are identical to those returned by sims_ocs, not an approximation. I believe I could also break out the slew subcomponents & cable wrap without much of a performance hit, but I'd have to take a closer look.

Should I look into the feasibility of this and then submit a pull request to sims_ocs that adds the speedObservatory slew time calculation (once I vectorize it)?

**Comment by rhiannonlynne** [comment]
I vectorized the slewtime calculation once, 
(see cell 3 at  https://github.com/rhiannonlynne/notebooks/blob/master/Slew%20Time%20Comparison.ipynb)
but feel free to improve! 

Your slew times are exact when there is no cable wrap (which I think is a rare occurence, but there is no allowance for that in your code), and there is something additional sims_ocs is doing about the orientation of the camera that I didn't manage to recreate in ts_observatory_model I believe (which is why my attempt to recreate the slew times using ts_observatory_model directly didn't match). 
I would like to understand what sims_ocs is doing about the camera rotation angle and have that be more transparent. (I suspect all it is doing is "not changing it during a slew", while my ts_observatory_model attempt kept the sky rotation angle constant ... I think .. but having a way make it clear what's going on would be helpful).

What were the speedups for the cloud and seeing computation? If it's getting the data ahead of time to build the lookup table, I suspect that may not get back into the sims_ocs code just because it's not really mocking how the telemetry comes in .. maybe a reasonable design decision, but can think about it.

**Comment by tribeiro** [comment]
This is an interesting discussion but I think we are going a bit off-topic here. Maybe it would be good to open an issue on sims_ocs repository and have the discussion there instead. 

Regarding this PR, one could also just not allow the user to have these features if sims_ocs is not installed (like @yoachim did on the no_ocs branch). If you prefer that as having this piece of code imported here, that can work as well. 

I just think it would be nice to have this option and, as things stands right now, seems like a good compromise.

**Comment by dhroth** [comment]
@tribeiro another option is to try/except the sims_ocs importsand then raise an exception if the user tries to call a function that relies on sims_ocs but sims_ocs failed to import (so that they don't unwittingly get back e.g. 0 seeing).

Sorry if the below is too far afield from this PR -- happy to move elsewhere if you send me a link
@rhiannonlynne thanks for that link! Sorry I misunderstood what you meant by approximate. I didn't include cable wrap originally because it's not an issue for sims_altSched (our scheduler never maxes out cable wrap), but we'd definitely need it if this code is going into sims_ocs. I would probably implement it as allowing a range of azimuths greater than 2pi and then deciding which of potentially two possible slews is shorter.

I also didn't include rotator angle yet but could add it if we're moving this code into sims_ocs. I just took a look at the sims_ocs code and got mired in a bunch of code I don't understand. Definitely agree with you re transparency... It should just be another uam component, no?

The sims_ocs speedups were just using binary search instead of linear search to find the date that was requested in the databases. I think it was Michael who merged it.

**Comment by tribeiro** [comment]
Hi @dhroth, I actually tried it first and, unfortunately, it wouldn't work either. Problem is Speed_observatory calls those module during __init__. So, that means you could import the module but won't be able to use it. 

I think I  found a better solution that problem. It may not be the best one, but at least it make it possible to use the module without sims.ocs. 

I stated by try/except loading sims.ocs modules and issuing a warning. Then, Speed_observatory receives the sims_ocs dependencies as argument. The default is that they are None, in which case, it will fall back to sims.ocs. But, the user has now the ability to have separate modules passed to the class. 

I created a local repository with the required pieces of code purged from sims.ocs and tested it. It worked pretty fine. I'll replace it here for your consideration.

**Comment by rhiannonlynne** [comment]
Thanks @tribeiro .. I think this solution is not perfect (better to avoid duplicating code, better to remove the need for speedObservatory, etc) - but it's good for now and we'll add it. This gets you access to weather/downtime/seeing, right?

**Comment by tribeiro** [comment]
Hi @rhiannonlynne , yes, it is possible to get access to those infos without sims_ocs. This final solution definitively avoids code duplication and I agree 💯 % with the other options.

**Pull request merged**
